from enum import IntEnum

from python_common.constants.enums import AuditLogModules, AuditLogScenario

class BaseEnum(IntEnum):
    @classmethod
    def choices(cls):
        return [(e.value, e.name.replace('_', ' ').title()) for e in cls]
    
class UserRole(BaseEnum):
    ANALYST = 1
    ADMIN = 2
    MANAGER = 3
    SUPER_ADMIN = 4
    VIEWER=5

class Platform(BaseEnum):
    AMD = 1
    BESS = 2

class DigestScope(BaseEnum):
    PER_ASSET = 1
    PER_ORGANIZATION = 2
    PORTFOLIO_WIDE = 3

class DigestFrequency(BaseEnum):
    DAILY = 1
    WEEKLY = 2
    MONTHLY = 3

class DigestStatus(BaseEnum):
    ACTIVE = 1
    INACTIVE = 0

class DigestResource(BaseEnum):
    ASSET = 1
    ORGANIZATION = 2
    PORTFOLIO = 3


class AssetStatus(BaseEnum):
    ACTIVE = 1
    INACTIVE = 2
    ANALYSIS_READY = 3
    DRAFT = 4
    PENDING_APPROVAL = 5

class AssetSteps(BaseEnum):
    BASIC_INFORMATION = 1
    OPTIMIZATION_CONFIGURATION = 2
    UPLOAD_AGGREGATOR_SCADA = 3
    IAR_REPORT = 4
    REVIEW = 5

class AssetType(BaseEnum):
    SOLAR = 1
    BATTERY = 2
    SOLAR_BATTERY = 3

class AssetFileType(BaseEnum):
    AGGREGATOR_REPORT = 1
    SCADA_REPORT = 2
    MERGED_SCADA_AGGREGATOR = 3
    INTERNAL_APPRAISAL_REPORT=4
    OPTIMIZED_DATASET=5

class AssetMetrics(BaseEnum):
    ASSET_REVENUE = 1
    CAPACITY_MARKET = 2
    DUOS_CREDIT = 3
    DUOS_FIXED_CHARGES = 4
    TOTAL_REVENUE = 5
    MODO_BENCHMARK = 6
    REVENUE_PER_MW_PER_YEAR = 7
    DAILY_CYCLES = 8
    ROUND_TRIP_EFFICIENCY = 9
    IAR_PROJECTION = 10
    TB_SPREAD_REVENUE = 11

class InvoiceType(BaseEnum):
    HARTREE_PV         = 1
    HARTREE_BESS       = 2
    EMR                = 3
    GRIDBEYOND         = 4
    HARTREE_BESS_POWER = 5
    HARTREE_AUXILIARY  = 6
    HARTREE_SOLAR_POWER = 7
    HARTREE_OTHER      = 8

class APDAuditLogScenario(BaseEnum):
    OTP_SENT = AuditLogScenario.OTP_SENT.value
    OTP_VERIFY_FAILED = AuditLogScenario.OTP_VERIFY_FAILED.value
    OTP_VERIFY_SUCCESS = AuditLogScenario.OTP_VERIFY_SUCCESS.value
    LOGIN_SUCCESS = AuditLogScenario.LOGIN_SUCCESS.value
    LOGIN_FAILED = AuditLogScenario.LOGIN_FAILED.value
    UNAUTHORIZED_ATTEMPT = AuditLogScenario.UNAUTHORIZED_ATTEMPT.value
    SESSION_STARTED = AuditLogScenario.SESSION_STARTED.value
    SESSION_IDLE_TIMEOUT = AuditLogScenario.SESSION_IDLE_TIMEOUT.value
    SESSION_ABS_TIMEOUT = AuditLogScenario.SESSION_ABS_TIMEOUT.value
    LOGOUT = AuditLogScenario.LOGOUT.value
    ORG_ASSIGNED = AuditLogScenario.ORG_ASSIGNED.value
    ORG_REASSIGNED = AuditLogScenario.ORG_REASSIGNED.value
    ORG_CREATED = AuditLogScenario.ORG_CREATED.value
    ORG_EDITED = AuditLogScenario.ORG_EDITED.value
    ORG_INACTIVATED = AuditLogScenario.ORG_INACTIVATED.value
    ORG_ENABLED = AuditLogScenario.ORG_ENABLED.value
    ORG_UPDATED = AuditLogScenario.ORG_UPDATED.value
    ASSET_REASSIGNED = AuditLogScenario.ASSET_REASSIGNED.value
    DIGEST_CREATED = AuditLogScenario.DIGEST_CREATED.value
    DIGEST_UPDATED = AuditLogScenario.DIGEST_UPDATED.value
    DIGEST_ACTIVATED = AuditLogScenario.DIGEST_ACTIVATED.value
    DIGEST_DEACTIVATED = AuditLogScenario.DIGEST_DEACTIVATED.value
    RECIPIENTS_UPDATED = AuditLogScenario.RECIPIENTS_UPDATED.value
    ASSET_ONBOARDED = AuditLogScenario.ASSET_ONBOARDED.value
    ASSET_UPDATED = AuditLogScenario.ASSET_UPDATED.value
    ASSET_OPTIMIZATION_UPDATED = AuditLogScenario.ASSET_OPTIMIZATION_UPDATED.value
    SCADA_REPORT_UPLOADED = AuditLogScenario.SCADA_REPORT_UPLOADED.value
    SCADA_REPORT_REMOVED = AuditLogScenario.SCADA_REPORT_REMOVED.value
    DATASET_MERGED = AuditLogScenario.DATASET_MERGED.value
    AGGREGATOR_REPORT_REMOVED = AuditLogScenario.AGGREGATOR_REPORT_REMOVED.value
    BENCHMARK_CONFIGURATION_UPDATED = AuditLogScenario.BENCHMARK_CONFIGURATION_UPDATED.value
    INTERNAL_APPRAISAL_REPORT_REMOVED = AuditLogScenario.INTERNAL_APPRAISAL_REPORT_REMOVED.value
    VIEWED_ASSET_BASIC_INFORMATION = AuditLogScenario.VIEWED_ASSET_BASIC_INFORMATION.value
    OPTIMIZATION_PARAMETERS_CONFIRMED = AuditLogScenario.OPTIMIZATION_PARAMETERS_CONFIRMED.value
    AGGREGATOR_FILE_UPLOADED = AuditLogScenario.AGGREGATOR_FILE_UPLOADED.value
    AGGREGATOR_FILE_REPLACED = AuditLogScenario.AGGREGATOR_FILE_REPLACED.value
    SCADA_FILE_REPLACED = AuditLogScenario.SCADA_FILE_REPLACED.value
    OPTIMIZED_DATASET_GENERATED = AuditLogScenario.OPTIMIZED_DATASET_GENERATED.value
    MERGED_DATASET_DOWNLOADED = AuditLogScenario.MERGED_DATASET_DOWNLOADED.value
    OPTIMIZED_DATASET_DOWNLOADED = AuditLogScenario.OPTIMIZED_DATASET_DOWNLOADED.value
    VIEWED_ASSET_ANALYSIS = AuditLogScenario.VIEWED_ASSET_ANALYSIS.value
    IAR_FILE_UPLOADED = AuditLogScenario.IAR_FILE_UPLOADED.value
    IAR_FILE_REPLACED = AuditLogScenario.IAR_FILE_REPLACED.value
    VIEWED_BENCHMARK_ANALYSIS = AuditLogScenario.VIEWED_BENCHMARK_ANALYSIS.value
    ASSET_SUBMITTED_FOR_APPROVAL = AuditLogScenario.ASSET_SUBMITTED_FOR_APPROVAL.value
    VIEWED_PENDING_APPROVAL_ASSET = AuditLogScenario.VIEWED_PENDING_APPROVAL_ASSET.value
    VIEWED_ACTIVE_ASSET = AuditLogScenario.VIEWED_ACTIVE_ASSET.value
    MONTHLY_AGGREGATOR_FILE_UPLOADED = AuditLogScenario.MONTHLY_AGGREGATOR_FILE_UPLOADED.value
    MONTHLY_SCADA_FILE_UPLOADED = AuditLogScenario.MONTHLY_SCADA_FILE_UPLOADED.value
    MONTHLY_AGGREGATOR_FILE_REPLACED = AuditLogScenario.MONTHLY_AGGREGATOR_FILE_REPLACED.value
    MONTHLY_SCADA_FILE_REPLACED = AuditLogScenario.MONTHLY_SCADA_FILE_REPLACED.value
    UPDATED_IAR_FILE = AuditLogScenario.UPDATED_IAR_FILE.value
    DOWNLOADED_AGGREGATOR_FILE = AuditLogScenario.DOWNLOADED_AGGREGATOR_FILE.value
    DOWNLOADED_SCADA_FILE = AuditLogScenario.DOWNLOADED_SCADA_FILE.value
    DOWNLOADED_IAR_FILE = AuditLogScenario.DOWNLOADED_IAR_FILE.value
    VIEWED_ASSET_APPROVAL_DETAILS = AuditLogScenario.VIEWED_ASSET_APPROVAL_DETAILS.value
    ASSET_APPROVED = AuditLogScenario.ASSET_APPROVED.value
    ASSET_DISABLED = AuditLogScenario.ASSET_DISABLED.value
    ASSET_ENABLED = AuditLogScenario.ASSET_ENABLED.value
    MONTHLY_METRIC_CREATED = AuditLogScenario.MONTHLY_METRIC_CREATED.value
    MONTHLY_METRIC_UPDATED = AuditLogScenario.MONTHLY_METRIC_UPDATED.value
    MONTHLY_METRIC_CLEARED = AuditLogScenario.MONTHLY_METRIC_CLEARED.value
    INVOICE_UPLOADED=AuditLogScenario.INVOICE_UPLOADED.value
    INVOICE_DELETED=AuditLogScenario.INVOICE_DELETED.value
    SETTLEMENT_FILE_UPLOADED=AuditLogScenario.SETTLEMENT_FILE_UPLOADED.value
    SETTLEMENT_FILE_DELETED=AuditLogScenario.SETTLEMENT_FILE_DELETED.value
    INVOICE_FILE_DOWNLOADED = AuditLogScenario.INVOICE_FILE_DOWNLOADED.value
    SETTLEMENT_FILE_DOWNLOADED = AuditLogScenario.SETTLEMENT_FILE_DOWNLOADED.value
    INVOICE_PREVIEW_DOWNLOADED = AuditLogScenario.INVOICE_PREVIEW_DOWNLOADED.value
    INVOICE_ANALYSIS_VIEWED = AuditLogScenario.INVOICE_ANALYSIS_VIEWED.value
    INVOICE_ANALYSIS_DATA_DOWNLOADED = AuditLogScenario.INVOICE_ANALYSIS_DATA_DOWNLOADED.value

class APDAuditLogModules(BaseEnum):
    AUTHENTICATION = AuditLogModules.AUTHENTICATION.value
    USER_MANAGEMENT = AuditLogModules.USER_MANAGEMENT_AMD.value
    ASSET_MANAGEMENT_AMD = AuditLogModules.ASSET_MANAGEMENT_AMD.value
    DIGEST_MANAGEMENT_AMD = AuditLogModules.DIGEST_MANAGEMENT_AMD.value
    ORGANIZATION_MANAGEMENT_AMD = AuditLogModules.ORGANIZATION_MANAGEMENT_AMD.value
    BENCHMARK_CONFIGURATION = AuditLogModules.BENCHMARK_CONFIGURATION.value
    MONTHLY_VALUE_MANAGEMENT_AMD = AuditLogModules.MONTHLY_VALUE_MANAGEMENT_AMD.value
    ASSET_ONBOARDING = AuditLogModules.ASSET_ONBOARDING.value
    VIEW_ANALYSIS = AuditLogModules.VIEW_ANALYSIS.value
    BENCHMARK_ANALYSIS = AuditLogModules.BENCHMARK_ANALYSIS.value
    INVOICE_ANALYSIS = AuditLogModules.INVOICE_ANALYSIS.value
