from .enums import Country

countries_list = {
    Country.AFGHANISTAN: {"label": "Afghanistan", "country_code": "AF", "currency_code": "AFN", "currency_symbol": "؋", "dial_code": "+93"},
    Country.ALBANIA: {"label": "Albania", "country_code": "AL", "currency_code": "ALL", "currency_symbol": "L", "dial_code": "+355"},
    Country.ALGERIA: {"label": "Algeria", "country_code": "DZ", "currency_code": "DZD", "currency_symbol": "دج", "dial_code": "+213"},
    Country.ANDORRA: {"label": "Andorra", "country_code": "AD", "currency_code": "EUR", "currency_symbol": "€", "dial_code": "+376"},
    Country.ANGOLA: {"label": "Angola", "country_code": "AO", "currency_code": "AOA", "currency_symbol": "Kz", "dial_code": "+244"},
    Country.ANTIGUA_AND_BARBUDA: {"label": "Antigua and Barbuda", "country_code": "AG", "currency_code": "XCD", "currency_symbol": "$", "dial_code": "+1-268"},
    Country.ARGENTINA: {"label": "Argentina", "country_code": "AR", "currency_code": "ARS", "currency_symbol": "$", "dial_code": "+54"},
    Country.ARMENIA: {"label": "Armenia", "country_code": "AM", "currency_code": "AMD", "currency_symbol": "֏", "dial_code": "+374"},
    Country.AUSTRALIA: {"label": "Australia", "country_code": "AU", "currency_code": "AUD", "currency_symbol": "$", "dial_code": "+61"},
    Country.AUSTRIA: {"label": "Austria", "country_code": "AT", "currency_code": "EUR", "currency_symbol": "€", "dial_code": "+43"},
    Country.AZERBAIJAN: {"label": "Azerbaijan", "country_code": "AZ", "currency_code": "AZN", "currency_symbol": "₼", "dial_code": "+994"},
    Country.BAHAMAS: {"label": "Bahamas", "country_code": "BS", "currency_code": "BSD", "currency_symbol": "$", "dial_code": "+1-242"},
    Country.BAHRAIN: {"label": "Bahrain", "country_code": "BH", "currency_code": "BHD", "currency_symbol": ".د.ب", "dial_code": "+973"},
    Country.BANGLADESH: {"label": "Bangladesh", "country_code": "BD", "currency_code": "BDT", "currency_symbol": "৳", "dial_code": "+880"},
    Country.BARBADOS: {"label": "Barbados", "country_code": "BB", "currency_code": "BBD", "currency_symbol": "$", "dial_code": "+1-246"},
    Country.BELARUS: {"label": "Belarus", "country_code": "BY", "currency_code": "BYN", "currency_symbol": "Br", "dial_code": "+375"},
    Country.BELGIUM: {"label": "Belgium", "country_code": "BE", "currency_code": "EUR", "currency_symbol": "€", "dial_code": "+32"},
    Country.BELIZE: {"label": "Belize", "country_code": "BZ", "currency_code": "BZD", "currency_symbol": "$", "dial_code": "+501"},
    Country.BENIN: {"label": "Benin", "country_code": "BJ", "currency_code": "XOF", "currency_symbol": "CFA", "dial_code": "+229"},
    Country.BHUTAN: {"label": "Bhutan", "country_code": "BT", "currency_code": "BTN", "currency_symbol": "Nu.", "dial_code": "+975"},
    Country.BOLIVIA: {"label": "Bolivia", "country_code": "BO", "currency_code": "BOB", "currency_symbol": "Bs.", "dial_code": "+591"},
    Country.BOSNIA_AND_HERZEGOVINA: {"label": "Bosnia and Herzegovina", "country_code": "BA", "currency_code": "BAM", "currency_symbol": "KM", "dial_code": "+387"},
    Country.BOTSWANA: {"label": "Botswana", "country_code": "BW", "currency_code": "BWP", "currency_symbol": "P", "dial_code": "+267"},
    Country.BRAZIL: {"label": "Brazil", "country_code": "BR", "currency_code": "BRL", "currency_symbol": "R$", "dial_code": "+55"},
    Country.BRUNEI: {"label": "Brunei", "country_code": "BN", "currency_code": "BND", "currency_symbol": "$", "dial_code": "+673"},
    Country.BULGARIA: {"label": "Bulgaria", "country_code": "BG", "currency_code": "BGN", "currency_symbol": "лв", "dial_code": "+359"},
    Country.BURKINA_FASO: {"label": "Burkina Faso", "country_code": "BF", "currency_code": "XOF", "currency_symbol": "CFA", "dial_code": "+226"},
    Country.BURUNDI: {"label": "Burundi", "country_code": "BI", "currency_code": "BIF", "currency_symbol": "Fr", "dial_code": "+257"},
    Country.CABO_VERDE: {"label": "Cabo Verde", "country_code": "CV", "currency_code": "CVE", "currency_symbol": "$", "dial_code": "+238"},
    Country.CAMBODIA: {"label": "Cambodia", "country_code": "KH", "currency_code": "KHR", "currency_symbol": "៛", "dial_code": "+855"},
    Country.CAMEROON: {"label": "Cameroon", "country_code": "CM", "currency_code": "XAF", "currency_symbol": "CFA", "dial_code": "+237"},
    Country.CANADA: {"label": "Canada", "country_code": "CA", "currency_code": "CAD", "currency_symbol": "$", "dial_code": "+1"},
    Country.CENTRAL_AFRICAN_REPUBLIC: {"label": "Central African Republic", "country_code": "CF", "currency_code": "XAF", "currency_symbol": "CFA", "dial_code": "+236"},
    Country.CHAD: {"label": "Chad", "country_code": "TD", "currency_code": "XAF", "currency_symbol": "CFA", "dial_code": "+235"},
    Country.CHILE: {"label": "Chile", "country_code": "CL", "currency_code": "CLP", "currency_symbol": "$", "dial_code": "+56"},
    Country.CHINA: {"label": "China", "country_code": "CN", "currency_code": "CNY", "currency_symbol": "¥", "dial_code": "+86"},
    Country.COLOMBIA: {"label": "Colombia", "country_code": "CO", "currency_code": "COP", "currency_symbol": "$", "dial_code": "+57"},
    Country.COMOROS: {"label": "Comoros", "country_code": "KM", "currency_code": "KMF", "currency_symbol": "Fr", "dial_code": "+269"},
    Country.CONGO_DEMOCRATIC_REPUBLIC: {"label": "Congo (Democratic Republic)", "country_code": "CD", "currency_code": "CDF", "currency_symbol": "Fr", "dial_code": "+243"},
    Country.CONGO_REPUBLIC: {"label": "Congo (Republic)", "country_code": "CG", "currency_code": "XAF", "currency_symbol": "CFA", "dial_code": "+242"},
    Country.COSTA_RICA: {"label": "Costa Rica", "country_code": "CR", "currency_code": "CRC", "currency_symbol": "₡", "dial_code": "+506"},
    Country.CROATIA: {"label": "Croatia", "country_code": "HR", "currency_code": "EUR", "currency_symbol": "€", "dial_code": "+385"},
    Country.CUBA: {"label": "Cuba", "country_code": "CU", "currency_code": "CUP", "currency_symbol": "$", "dial_code": "+53"},
    Country.CYPRUS: {"label": "Cyprus", "country_code": "CY", "currency_code": "EUR", "currency_symbol": "€", "dial_code": "+357"},
    Country.CZECH_REPUBLIC: {"label": "Czech Republic", "country_code": "CZ", "currency_code": "CZK", "currency_symbol": "Kč", "dial_code": "+420"},
    Country.DENMARK: {"label": "Denmark", "country_code": "DK", "currency_code": "DKK", "currency_symbol": "kr", "dial_code": "+45"},
    Country.DJIBOUTI: {"label": "Djibouti", "country_code": "DJ", "currency_code": "DJF", "currency_symbol": "Fr", "dial_code": "+253"},
    Country.DOMINICA: {"label": "Dominica", "country_code": "DM", "currency_code": "XCD", "currency_symbol": "$", "dial_code": "+1-767"},
    Country.DOMINICAN_REPUBLIC: {"label": "Dominican Republic", "country_code": "DO", "currency_code": "DOP", "currency_symbol": "RD$", "dial_code": "+1-809"},
    Country.ECUADOR: {"label": "Ecuador", "country_code": "EC", "currency_code": "USD", "currency_symbol": "$", "dial_code": "+593"},
    Country.EGYPT: {"label": "Egypt", "country_code": "EG", "currency_code": "EGP", "currency_symbol": "£", "dial_code": "+20"},
    Country.EL_SALVADOR: {"label": "El Salvador", "country_code": "SV", "currency_code": "USD", "currency_symbol": "$", "dial_code": "+503"},
    Country.EQUATORIAL_GUINEA: {"label": "Equatorial Guinea", "country_code": "GQ", "currency_code": "XAF", "currency_symbol": "CFA", "dial_code": "+240"},
    Country.ERITREA: {"label": "Eritrea", "country_code": "ER", "currency_code": "ERN", "currency_symbol": "Nfk", "dial_code": "+291"},
    Country.ESTONIA: {"label": "Estonia", "country_code": "EE", "currency_code": "EUR", "currency_symbol": "€", "dial_code": "+372"},
    Country.ESWATINI: {"label": "Eswatini", "country_code": "SZ", "currency_code": "SZL", "currency_symbol": "L", "dial_code": "+268"},
    Country.ETHIOPIA: {"label": "Ethiopia", "country_code": "ET", "currency_code": "ETB", "currency_symbol": "Br", "dial_code": "+251"},
    Country.FIJI: {"label": "Fiji", "country_code": "FJ", "currency_code": "FJD", "currency_symbol": "$", "dial_code": "+679"},
    Country.FINLAND: {"label": "Finland", "country_code": "FI", "currency_code": "EUR", "currency_symbol": "€", "dial_code": "+358"},
    Country.FRANCE: {"label": "France", "country_code": "FR", "currency_code": "EUR", "currency_symbol": "€", "dial_code": "+33"},
    Country.GABON: {"label": "Gabon", "country_code": "GA", "currency_code": "XAF", "currency_symbol": "CFA", "dial_code": "+241"},
    Country.GAMBIA: {"label": "Gambia", "country_code": "GM", "currency_code": "GMD", "currency_symbol": "D", "dial_code": "+220"},
    Country.GEORGIA: {"label": "Georgia", "country_code": "GE", "currency_code": "GEL", "currency_symbol": "₾", "dial_code": "+995"},
    Country.GERMANY: {"label": "Germany", "country_code": "DE", "currency_code": "EUR", "currency_symbol": "€", "dial_code": "+49"},
    Country.GHANA: {"label": "Ghana", "country_code": "GH", "currency_code": "GHS", "currency_symbol": "₵", "dial_code": "+233"},
    Country.GREECE: {"label": "Greece", "country_code": "GR", "currency_code": "EUR", "currency_symbol": "€", "dial_code": "+30"},
    Country.GRENADA: {"label": "Grenada", "country_code": "GD", "currency_code": "XCD", "currency_symbol": "$", "dial_code": "+1-473"},
    Country.GUATEMALA: {"label": "Guatemala", "country_code": "GT", "currency_code": "GTQ", "currency_symbol": "Q", "dial_code": "+502"},
    Country.GUINEA: {"label": "Guinea", "country_code": "GN", "currency_code": "GNF", "currency_symbol": "Fr", "dial_code": "+224"},
    Country.GUINEA_BISSAU: {"label": "Guinea-Bissau", "country_code": "GW", "currency_code": "XOF", "currency_symbol": "CFA", "dial_code": "+245"},
    Country.GUYANA: {"label": "Guyana", "country_code": "GY", "currency_code": "GYD", "currency_symbol": "$", "dial_code": "+592"},
    Country.HAITI: {"label": "Haiti", "country_code": "HT", "currency_code": "HTG", "currency_symbol": "G", "dial_code": "+509"},
    Country.HONDURAS: {"label": "Honduras", "country_code": "HN", "currency_code": "HNL", "currency_symbol": "L", "dial_code": "+504"},
    Country.HUNGARY: {"label": "Hungary", "country_code": "HU", "currency_code": "HUF", "currency_symbol": "Ft", "dial_code": "+36"},
    Country.ICELAND: {"label": "Iceland", "country_code": "IS", "currency_code": "ISK", "currency_symbol": "kr", "dial_code": "+354"},
    Country.INDIA: {"label": "India", "country_code": "IN", "currency_code": "INR", "currency_symbol": "₹", "dial_code": "+91"},
    Country.INDONESIA: {"label": "Indonesia", "country_code": "ID", "currency_code": "IDR", "currency_symbol": "Rp", "dial_code": "+62"},
    Country.IRAN: {"label": "Iran", "country_code": "IR", "currency_code": "IRR", "currency_symbol": "﷼", "dial_code": "+98"},
    Country.IRAQ: {"label": "Iraq", "country_code": "IQ", "currency_code": "IQD", "currency_symbol": "ع.د", "dial_code": "+964"},
    Country.IRELAND: {"label": "Ireland", "country_code": "IE", "currency_code": "EUR", "currency_symbol": "€", "dial_code": "+353"},
    Country.ISRAEL: {"label": "Israel", "country_code": "IL", "currency_code": "ILS", "currency_symbol": "₪", "dial_code": "+972"},
    Country.ITALY: {"label": "Italy", "country_code": "IT", "currency_code": "EUR", "currency_symbol": "€", "dial_code": "+39"},
    Country.JAMAICA: {"label": "Jamaica", "country_code": "JM", "currency_code": "JMD", "currency_symbol": "$", "dial_code": "+1-876"},
    Country.JAPAN: {"label": "Japan", "country_code": "JP", "currency_code": "JPY", "currency_symbol": "¥", "dial_code": "+81"},
    Country.JORDAN: {"label": "Jordan", "country_code": "JO", "currency_code": "JOD", "currency_symbol": "د.ا", "dial_code": "+962"},
    Country.KAZAKHSTAN: {"label": "Kazakhstan", "country_code": "KZ", "currency_code": "KZT", "currency_symbol": "₸", "dial_code": "+7"},
    Country.KENYA: {"label": "Kenya", "country_code": "KE", "currency_code": "KES", "currency_symbol": "Sh", "dial_code": "+254"},
    Country.KIRIBATI: {"label": "Kiribati", "country_code": "KI", "currency_code": "AUD", "currency_symbol": "$", "dial_code": "+686"},
    Country.KOREA_NORTH: {"label": "Korea (North)", "country_code": "KP", "currency_code": "KPW", "currency_symbol": "₩", "dial_code": "+850"},
    Country.KOREA_SOUTH: {"label": "Korea (South)", "country_code": "KR", "currency_code": "KRW", "currency_symbol": "₩", "dial_code": "+82"},
    Country.KUWAIT: {"label": "Kuwait", "country_code": "KW", "currency_code": "KWD", "currency_symbol": "د.ك", "dial_code": "+965"},
    Country.KYRGYZSTAN: {"label": "Kyrgyzstan", "country_code": "KG", "currency_code": "KGS", "currency_symbol": "лв", "dial_code": "+996"},
    Country.LAOS: {"label": "Laos", "country_code": "LA", "currency_code": "LAK", "currency_symbol": "₭", "dial_code": "+856"},
    Country.LATVIA: {"label": "Latvia", "country_code": "LV", "currency_code": "EUR", "currency_symbol": "€", "dial_code": "+371"},
    Country.LEBANON: {"label": "Lebanon", "country_code": "LB", "currency_code": "LBP", "currency_symbol": "£", "dial_code": "+961"},
    Country.LESOTHO: {"label": "Lesotho", "country_code": "LS", "currency_code": "LSL", "currency_symbol": "L", "dial_code": "+266"},
    Country.LIBERIA: {"label": "Liberia", "country_code": "LR", "currency_code": "LRD", "currency_symbol": "$", "dial_code": "+231"},
    Country.LIBYA: {"label": "Libya", "country_code": "LY", "currency_code": "LYD", "currency_symbol": "ل.د", "dial_code": "+218"},
    Country.LIECHTENSTEIN: {"label": "Liechtenstein", "country_code": "LI", "currency_code": "CHF", "currency_symbol": "CHF", "dial_code": "+423"},
    Country.LITHUANIA: {"label": "Lithuania", "country_code": "LT", "currency_code": "EUR", "currency_symbol": "€", "dial_code": "+370"},
    Country.LUXEMBOURG: {"label": "Luxembourg", "country_code": "LU", "currency_code": "EUR", "currency_symbol": "€", "dial_code": "+352"},
    Country.MADAGASCAR: {"label": "Madagascar", "country_code": "MG", "currency_code": "MGA", "currency_symbol": "Ar", "dial_code": "+261"},
    Country.MALAWI: {"label": "Malawi", "country_code": "MW", "currency_code": "MWK", "currency_symbol": "MK", "dial_code": "+265"},
    Country.MALAYSIA: {"label": "Malaysia", "country_code": "MY", "currency_code": "MYR", "currency_symbol": "RM", "dial_code": "+60"},
    Country.MALDIVES: {"label": "Maldives", "country_code": "MV", "currency_code": "MVR", "currency_symbol": "Rf", "dial_code": "+960"},
    Country.MALI: {"label": "Mali", "country_code": "ML", "currency_code": "XOF", "currency_symbol": "CFA", "dial_code": "+223"},
    Country.MALTA: {"label": "Malta", "country_code": "MT", "currency_code": "EUR", "currency_symbol": "€", "dial_code": "+356"},
    Country.MARSHALL_ISLANDS: {"label": "Marshall Islands", "country_code": "MH", "currency_code": "USD", "currency_symbol": "$", "dial_code": "+692"},
    Country.MAURITANIA: {"label": "Mauritania", "country_code": "MR", "currency_code": "MRU", "currency_symbol": "UM", "dial_code": "+222"},
    Country.MAURITIUS: {"label": "Mauritius", "country_code": "MU", "currency_code": "MUR", "currency_symbol": "₨", "dial_code": "+230"},
    Country.MEXICO: {"label": "Mexico", "country_code": "MX", "currency_code": "MXN", "currency_symbol": "$", "dial_code": "+52"},
    Country.MICRONESIA: {"label": "Micronesia", "country_code": "FM", "currency_code": "USD", "currency_symbol": "$", "dial_code": "+691"},
    Country.MOLDOVA: {"label": "Moldova", "country_code": "MD", "currency_code": "MDL", "currency_symbol": "L", "dial_code": "+373"},
    Country.MONACO: {"label": "Monaco", "country_code": "MC", "currency_code": "EUR", "currency_symbol": "€", "dial_code": "+377"},
    Country.MONGOLIA: {"label": "Mongolia", "country_code": "MN", "currency_code": "MNT", "currency_symbol": "₮", "dial_code": "+976"},
    Country.MONTENEGRO: {"label": "Montenegro", "country_code": "ME", "currency_code": "EUR", "currency_symbol": "€", "dial_code": "+382"},
    Country.MOROCCO: {"label": "Morocco", "country_code": "MA", "currency_code": "MAD", "currency_symbol": "د.م.", "dial_code": "+212"},
    Country.MOZAMBIQUE: {"label": "Mozambique", "country_code": "MZ", "currency_code": "MZN", "currency_symbol": "MT", "dial_code": "+258"},
    Country.MYANMAR: {"label": "Myanmar", "country_code": "MM", "currency_code": "MMK", "currency_symbol": "K", "dial_code": "+95"},
    Country.NAMIBIA: {"label": "Namibia", "country_code": "NA", "currency_code": "NAD", "currency_symbol": "$", "dial_code": "+264"},
    Country.NAURU: {"label": "Nauru", "country_code": "NR", "currency_code": "AUD", "currency_symbol": "$", "dial_code": "+674"},
    Country.NEPAL: {"label": "Nepal", "country_code": "NP", "currency_code": "NPR", "currency_symbol": "₨", "dial_code": "+977"},
    Country.NETHERLANDS: {"label": "Netherlands", "country_code": "NL", "currency_code": "EUR", "currency_symbol": "€", "dial_code": "+31"},
    Country.NEW_ZEALAND: {"label": "New Zealand", "country_code": "NZ", "currency_code": "NZD", "currency_symbol": "$", "dial_code": "+64"},
    Country.NICARAGUA: {"label": "Nicaragua", "country_code": "NI", "currency_code": "NIO", "currency_symbol": "C$", "dial_code": "+505"},
    Country.NIGER: {"label": "Niger", "country_code": "NE", "currency_code": "XOF", "currency_symbol": "CFA", "dial_code": "+227"},
    Country.NIGERIA: {"label": "Nigeria", "country_code": "NG", "currency_code": "NGN", "currency_symbol": "₦", "dial_code": "+234"},
    Country.NORTH_MACEDONIA: {"label": "North Macedonia", "country_code": "MK", "currency_code": "MKD", "currency_symbol": "ден", "dial_code": "+389"},
    Country.NORWAY: {"label": "Norway", "country_code": "NO", "currency_code": "NOK", "currency_symbol": "kr", "dial_code": "+47"},
    Country.OMAN: {"label": "Oman", "country_code": "OM", "currency_code": "OMR", "currency_symbol": "ر.ع.", "dial_code": "+968"},
    Country.PAKISTAN: {"label": "Pakistan", "country_code": "PK", "currency_code": "PKR", "currency_symbol": "₨", "dial_code": "+92"},
    Country.PALAU: {"label": "Palau", "country_code": "PW", "currency_code": "USD", "currency_symbol": "$", "dial_code": "+680"},
    Country.PANAMA: {"label": "Panama", "country_code": "PA", "currency_code": "PAB", "currency_symbol": "B/.", "dial_code": "+507"},
    Country.PAPUA_NEW_GUINEA: {"label": "Papua New Guinea", "country_code": "PG", "currency_code": "PGK", "currency_symbol": "K", "dial_code": "+675"},
    Country.PARAGUAY: {"label": "Paraguay", "country_code": "PY", "currency_code": "PYG", "currency_symbol": "₲", "dial_code": "+595"},
    Country.PERU: {"label": "Peru", "country_code": "PE", "currency_code": "PEN", "currency_symbol": "S/", "dial_code": "+51"},
    Country.PHILIPPINES: {"label": "Philippines", "country_code": "PH", "currency_code": "PHP", "currency_symbol": "₱", "dial_code": "+63"},
    Country.POLAND: {"label": "Poland", "country_code": "PL", "currency_code": "PLN", "currency_symbol": "zł", "dial_code": "+48"},
    Country.PORTUGAL: {"label": "Portugal", "country_code": "PT", "currency_code": "EUR", "currency_symbol": "€", "dial_code": "+351"},
    Country.QATAR: {"label": "Qatar", "country_code": "QA", "currency_code": "QAR", "currency_symbol": "﷼", "dial_code": "+974"},
    Country.ROMANIA: {"label": "Romania", "country_code": "RO", "currency_code": "RON", "currency_symbol": "lei", "dial_code": "+40"},
    Country.RUSSIA: {"label": "Russia", "country_code": "RU", "currency_code": "RUB", "currency_symbol": "₽", "dial_code": "+7"},
    Country.RWANDA: {"label": "Rwanda", "country_code": "RW", "currency_code": "RWF", "currency_symbol": "Fr", "dial_code": "+250"},
    Country.SAINT_KITTS_AND_NEVIS: {"label": "Saint Kitts and Nevis", "country_code": "KN", "currency_code": "XCD", "currency_symbol": "$", "dial_code": "+1-869"},
    Country.SAINT_LUCIA: {"label": "Saint Lucia", "country_code": "LC", "currency_code": "XCD", "currency_symbol": "$", "dial_code": "+1-758"},
    Country.SAINT_VINCENT_AND_THE_GRENADINES: {"label": "Saint Vincent and the Grenadines", "country_code": "VC", "currency_code": "XCD", "currency_symbol": "$", "dial_code": "+1-784"},
    Country.SAMOA: {"label": "Samoa", "country_code": "WS", "currency_code": "WST", "currency_symbol": "T", "dial_code": "+685"},
    Country.SAN_MARINO: {"label": "San Marino", "country_code": "SM", "currency_code": "EUR", "currency_symbol": "€", "dial_code": "+378"},
    Country.SAO_TOME_AND_PRINCIPE: {"label": "Sao Tome and Principe", "country_code": "ST", "currency_code": "STN", "currency_symbol": "Db", "dial_code": "+239"},
    Country.SAUDI_ARABIA: {"label": "Saudi Arabia", "country_code": "SA", "currency_code": "SAR", "currency_symbol": "﷼", "dial_code": "+966"},
    Country.SENEGAL: {"label": "Senegal", "country_code": "SN", "currency_code": "XOF", "currency_symbol": "CFA", "dial_code": "+221"},
    Country.SERBIA: {"label": "Serbia", "country_code": "RS", "currency_code": "RSD", "currency_symbol": "дин", "dial_code": "+381"},
    Country.SEYCHELLES: {"label": "Seychelles", "country_code": "SC", "currency_code": "SCR", "currency_symbol": "₨", "dial_code": "+248"},
    Country.SIERRA_LEONE: {"label": "Sierra Leone", "country_code": "SL", "currency_code": "SLL", "currency_symbol": "Le", "dial_code": "+232"},
    Country.SINGAPORE: {"label": "Singapore", "country_code": "SG", "currency_code": "SGD", "currency_symbol": "$", "dial_code": "+65"},
    Country.SLOVAKIA: {"label": "Slovakia", "country_code": "SK", "currency_code": "EUR", "currency_symbol": "€", "dial_code": "+421"},
    Country.SLOVENIA: {"label": "Slovenia", "country_code": "SI", "currency_code": "EUR", "currency_symbol": "€", "dial_code": "+386"},
    Country.SOLOMON_ISLANDS: {"label": "Solomon Islands", "country_code": "SB", "currency_code": "SBD", "currency_symbol": "$", "dial_code": "+677"},
    Country.SOMALIA: {"label": "Somalia", "country_code": "SO", "currency_code": "SOS", "currency_symbol": "Sh", "dial_code": "+252"},
    Country.SOUTH_AFRICA: {"label": "South Africa", "country_code": "ZA", "currency_code": "ZAR", "currency_symbol": "R", "dial_code": "+27"},
    Country.SOUTH_SUDAN: {"label": "South Sudan", "country_code": "SS", "currency_code": "SSP", "currency_symbol": "£", "dial_code": "+211"},
    Country.SPAIN: {"label": "Spain", "country_code": "ES", "currency_code": "EUR", "currency_symbol": "€", "dial_code": "+34"},
    Country.SRI_LANKA: {"label": "Sri Lanka", "country_code": "LK", "currency_code": "LKR", "currency_symbol": "Rs", "dial_code": "+94"},
    Country.SUDAN: {"label": "Sudan", "country_code": "SD", "currency_code": "SDG", "currency_symbol": "£", "dial_code": "+249"},
    Country.SURINAME: {"label": "Suriname", "country_code": "SR", "currency_code": "SRD", "currency_symbol": "$", "dial_code": "+597"},
    Country.SWEDEN: {"label": "Sweden", "country_code": "SE", "currency_code": "SEK", "currency_symbol": "kr", "dial_code": "+46"},
    Country.SWITZERLAND: {"label": "Switzerland", "country_code": "CH", "currency_code": "CHF", "currency_symbol": "CHF", "dial_code": "+41"},
    Country.SYRIA: {"label": "Syria", "country_code": "SY", "currency_code": "SYP", "currency_symbol": "£", "dial_code": "+963"},
    Country.TAIWAN: {"label": "Taiwan", "country_code": "TW", "currency_code": "TWD", "currency_symbol": "$", "dial_code": "+886"},
    Country.TAJIKISTAN: {"label": "Tajikistan", "country_code": "TJ", "currency_code": "TJS", "currency_symbol": "ЅМ", "dial_code": "+992"},
    Country.TANZANIA: {"label": "Tanzania", "country_code": "TZ", "currency_code": "TZS", "currency_symbol": "Sh", "dial_code": "+255"},
    Country.THAILAND: {"label": "Thailand", "country_code": "TH", "currency_code": "THB", "currency_symbol": "฿", "dial_code": "+66"},
    Country.TIMOR_LESTE: {"label": "Timor-Leste", "country_code": "TL", "currency_code": "USD", "currency_symbol": "$", "dial_code": "+670"},
    Country.TOGO: {"label": "Togo", "country_code": "TG", "currency_code": "XOF", "currency_symbol": "CFA", "dial_code": "+228"},
    Country.TONGA: {"label": "Tonga", "country_code": "TO", "currency_code": "TOP", "currency_symbol": "T$", "dial_code": "+676"},
    Country.TRINIDAD_AND_TOBAGO: {"label": "Trinidad and Tobago", "country_code": "TT", "currency_code": "TTD", "currency_symbol": "$", "dial_code": "+1-868"},
    Country.TUNISIA: {"label": "Tunisia", "country_code": "TN", "currency_code": "TND", "currency_symbol": "د.ت", "dial_code": "+216"},
    Country.TURKEY: {"label": "Turkey", "country_code": "TR", "currency_code": "TRY", "currency_symbol": "₺", "dial_code": "+90"},
    Country.TURKMENISTAN: {"label": "Turkmenistan", "country_code": "TM", "currency_code": "TMT", "currency_symbol": "m", "dial_code": "+993"},
    Country.TUVALU: {"label": "Tuvalu", "country_code": "TV", "currency_code": "AUD", "currency_symbol": "$", "dial_code": "+688"},
    Country.UGANDA: {"label": "Uganda", "country_code": "UG", "currency_code": "UGX", "currency_symbol": "Sh", "dial_code": "+256"},
    Country.UKRAINE: {"label": "Ukraine", "country_code": "UA", "currency_code": "UAH", "currency_symbol": "₴", "dial_code": "+380"},
    Country.UNITED_ARAB_EMIRATES: {"label": "United Arab Emirates", "country_code": "AE", "currency_code": "AED", "currency_symbol": "د.إ", "dial_code": "+971"},
    Country.UNITED_KINGDOM: {"label": "United Kingdom", "country_code": "GB", "currency_code": "GBP", "currency_symbol": "£", "dial_code": "+44"},
    Country.UNITED_STATES: {"label": "United States", "country_code": "US", "currency_code": "USD", "currency_symbol": "$", "dial_code": "+1"},
    Country.URUGUAY: {"label": "Uruguay", "country_code": "UY", "currency_code": "UYU", "currency_symbol": "$", "dial_code": "+598"},
    Country.UZBEKISTAN: {"label": "Uzbekistan", "country_code": "UZ", "currency_code": "UZS", "currency_symbol": "soʻm", "dial_code": "+998"},
    Country.VANUATU: {"label": "Vanuatu", "country_code": "VU", "currency_code": "VUV", "currency_symbol": "Vt", "dial_code": "+678"},
    Country.VATICAN_CITY: {"label": "Vatican City", "country_code": "VA", "currency_code": "EUR", "currency_symbol": "€", "dial_code": "+379"},
    Country.VENEZUELA: {"label": "Venezuela", "country_code": "VE", "currency_code": "VES", "currency_symbol": "Bs.", "dial_code": "+58"},
    Country.VIETNAM: {"label": "Vietnam", "country_code": "VN", "currency_code": "VND", "currency_symbol": "₫", "dial_code": "+84"},
    Country.YEMEN: {"label": "Yemen", "country_code": "YE", "currency_code": "YER", "currency_symbol": "﷼", "dial_code": "+967"},
    Country.ZAMBIA: {"label": "Zambia", "country_code": "ZM", "currency_code": "ZMW", "currency_symbol": "ZK", "dial_code": "+260"},
    Country.ZIMBABWE: {"label": "Zimbabwe", "country_code": "ZW", "currency_code": "ZWL", "currency_symbol": "$", "dial_code": "+263"},
}
